/// Input schemas this package declares, embedded so the always-on memory
/// lane can serve them without a materialized package root.
pub const MEMORY_SCHEMA_ASSETS: &[(&str, &str)] = &[
    (
        "schemas/knowledge/search.input.v1.json",
        include_str!("../schemas/knowledge/search.input.v1.json"),
    ),
    (
        "schemas/memory/search.input.v1.json",
        include_str!("../schemas/memory/search.input.v1.json"),
    ),
    (
        "schemas/mnesis/bootstrap.input.v1.json",
        include_str!("../schemas/mnesis/bootstrap.input.v1.json"),
    ),
    (
        "schemas/mnesis/challenge_retrieval.input.v1.json",
        include_str!("../schemas/mnesis/challenge_retrieval.input.v1.json"),
    ),
    (
        "schemas/mnesis/compilation_status.input.v1.json",
        include_str!("../schemas/mnesis/compilation_status.input.v1.json"),
    ),
    (
        "schemas/mnesis/consolidation.input.v1.json",
        include_str!("../schemas/mnesis/consolidation.input.v1.json"),
    ),
    (
        "schemas/mnesis/contradictions.input.v1.json",
        include_str!("../schemas/mnesis/contradictions.input.v1.json"),
    ),
    (
        "schemas/mnesis/decompile.input.v1.json",
        include_str!("../schemas/mnesis/decompile.input.v1.json"),
    ),
    (
        "schemas/mnesis/duplicates.input.v1.json",
        include_str!("../schemas/mnesis/duplicates.input.v1.json"),
    ),
    (
        "schemas/mnesis/feedback.input.v1.json",
        include_str!("../schemas/mnesis/feedback.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_context.input.v1.json",
        include_str!("../schemas/mnesis/get_context.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_decision.input.v1.json",
        include_str!("../schemas/mnesis/get_decision.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_evidence.input.v1.json",
        include_str!("../schemas/mnesis/get_evidence.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_execution_attestation.input.v1.json",
        include_str!("../schemas/mnesis/get_execution_attestation.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_sources.input.v1.json",
        include_str!("../schemas/mnesis/get_sources.input.v1.json"),
    ),
    (
        "schemas/mnesis/get_stats.input.v1.json",
        include_str!("../schemas/mnesis/get_stats.input.v1.json"),
    ),
    (
        "schemas/mnesis/health.input.v1.json",
        include_str!("../schemas/mnesis/health.input.v1.json"),
    ),
    (
        "schemas/mnesis/list_related.input.v1.json",
        include_str!("../schemas/mnesis/list_related.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_add_fact.input.v1.json",
        include_str!("../schemas/mnesis/memory_add_fact.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_add_learning.input.v1.json",
        include_str!("../schemas/mnesis/memory_add_learning.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_add_session.input.v1.json",
        include_str!("../schemas/mnesis/memory_add_session.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_export_obsidian_vault.input.v1.json",
        include_str!("../schemas/mnesis/memory_export_obsidian_vault.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_feedback.input.v1.json",
        include_str!("../schemas/mnesis/memory_feedback.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_graph_export.input.v1.json",
        include_str!("../schemas/mnesis/memory_graph_export.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_knowledge_gaps.input.v1.json",
        include_str!("../schemas/mnesis/memory_knowledge_gaps.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_query_related.input.v1.json",
        include_str!("../schemas/mnesis/memory_query_related.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_run_maintenance.input.v1.json",
        include_str!("../schemas/mnesis/memory_run_maintenance.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_stats.input.v1.json",
        include_str!("../schemas/mnesis/memory_stats.input.v1.json"),
    ),
    (
        "schemas/mnesis/memory_temporal_query.input.v1.json",
        include_str!("../schemas/mnesis/memory_temporal_query.input.v1.json"),
    ),
    (
        "schemas/mnesis/metrics.input.v1.json",
        include_str!("../schemas/mnesis/metrics.input.v1.json"),
    ),
    (
        "schemas/mnesis/promote.input.v1.json",
        include_str!("../schemas/mnesis/promote.input.v1.json"),
    ),
    (
        "schemas/mnesis/publish_corpus.input.v1.json",
        include_str!("../schemas/mnesis/publish_corpus.input.v1.json"),
    ),
    (
        "schemas/mnesis/publish_status.input.v1.json",
        include_str!("../schemas/mnesis/publish_status.input.v1.json"),
    ),
    (
        "schemas/mnesis/rar_export_obsidian_vault.input.v1.json",
        include_str!("../schemas/mnesis/rar_export_obsidian_vault.input.v1.json"),
    ),
    (
        "schemas/mnesis/reflex_add.input.v1.json",
        include_str!("../schemas/mnesis/reflex_add.input.v1.json"),
    ),
    (
        "schemas/mnesis/reflexes.input.v1.json",
        include_str!("../schemas/mnesis/reflexes.input.v1.json"),
    ),
    (
        "schemas/mnesis/routing.input.v1.json",
        include_str!("../schemas/mnesis/routing.input.v1.json"),
    ),
    (
        "schemas/mnesis/search.input.v1.json",
        include_str!("../schemas/mnesis/search.input.v1.json"),
    ),
    (
        "schemas/mnesis/speculative.input.v1.json",
        include_str!("../schemas/mnesis/speculative.input.v1.json"),
    ),
    (
        "schemas/mnesis/stale.input.v1.json",
        include_str!("../schemas/mnesis/stale.input.v1.json"),
    ),
    (
        "schemas/mnesis/submit_corpus.input.v1.json",
        include_str!("../schemas/mnesis/submit_corpus.input.v1.json"),
    ),
    (
        "schemas/mnesis/task_read.input.v1.json",
        include_str!("../schemas/mnesis/task_read.input.v1.json"),
    ),
    (
        "schemas/mnesis/task_update_status.input.v1.json",
        include_str!("../schemas/mnesis/task_update_status.input.v1.json"),
    ),
    (
        "schemas/mnesis/task_write.input.v1.json",
        include_str!("../schemas/mnesis/task_write.input.v1.json"),
    ),
    (
        "schemas/mnesis/training.input.v1.json",
        include_str!("../schemas/mnesis/training.input.v1.json"),
    ),
    (
        "schemas/mnesis/verify_grounding.input.v1.json",
        include_str!("../schemas/mnesis/verify_grounding.input.v1.json"),
    ),
];
